from typing import Annotated
from pydantic import BaseModel, Field


class RecentOrder(BaseModel):
    order_id: Annotated[str, Field(description="Unique identifier for the order", examples=["52fecfe4-c101-4d24-9f82-8d66f145dd1d"])]
    customer_name: Annotated[str, Field(description="Name of the customer who placed the order", examples=["John Doe"])]
    amount: Annotated[float, Field(description="Total amount for the order", examples=[250.50])]
    status: Annotated[str, Field(description="Current status of the order", examples=["delivered"])]

class TopProduct(BaseModel):
    name: Annotated[str, Field(description="Name of the product", examples=["Product A"])]
    sales: Annotated[int, Field(description="Total sales of the product", examples=[44])]
    revenue: Annotated[float, Field(description="Total revenue generated by the product", examples=[4400.00])]
    

class WithdrawalItem(BaseModel):

    id: Annotated[int, Field(description="Unique transaction ID", examples=[1])]
    description: Annotated[str, Field(description="Description or label for the withdrawal", examples=["Withdrawal to bank account"])]
    status: Annotated[str, Field(description="Transaction status (e.g., completed, pending, failed)", examples=["completed"])]
    amount: Annotated[float, Field(description="Negative value representing amount withdrawn", examples=[-1500.00])]
    date: Annotated[str | None, Field(None, description="Formatted date/time of the transaction", examples=["2025-04-01 10:30:00"])]


class WithdrawalHistory(BaseModel):

    items: Annotated[list[WithdrawalItem], Field(description="List of withdrawal transaction records", examples=[{"id": 1, "description": "Withdrawal to bank account", "status": "completed", "amount": -1500.00, "date": "2025-04-01 10:30:00"}])]
    page: Annotated[int, Field(description="Current page number in pagination", examples=[1])]
    page_size: Annotated[int, Field(description="Number of records returned per page", examples=[10])]
    total: Annotated[int, Field(description="Total number of withdrawal transactions available", examples=[50])]
    total_pages: Annotated[int, Field(description="Total number of pages available", examples=[5])]


class WalletDashboardResponse(BaseModel):

    available_balance: Annotated[float, Field(description="Funds currently available for use", examples=[5000.00])]
    pending_balance: Annotated[float, Field(description="Funds awaiting clearance or processing", examples=[2000.00])]
    withdrawable_balance: Annotated[float, Field(description="Funds that can be withdrawn immediately", examples=[3000.00])]
    withdrawal_history: Annotated[WithdrawalHistory, Field(description="Paginated withdrawal transaction history", examples={"items": [{"id": 1, "description": "Withdrawal to bank account", "status": "completed", "amount": -1500.00, "date": "2025-04-01 10:30:00"}], "page": 1, "page_size": 10, "total": 50, "total_pages": 5})]


class VendorOrderItem(BaseModel):
    id: Annotated[str, Field(description="Order ID formatted like ORD-001", examples=["ORD-001"])]
    buyer_name: Annotated[str, Field(description="Name of the buyer", examples=["John Doe"])]
    date: Annotated[str | None, Field(None, description="Date of order (dd-mm-yyyy)", examples=["25-12-2023"])]
    amount: Annotated[float, Field(description="Order amount in Naira", examples=[1500.00])]
    status: Annotated[str, Field(description="Current status of the order", examples=["completed", "processing", "pending"])]


class PaginatedOrders(BaseModel):
    items: Annotated[list[VendorOrderItem], Field(description="List of paginated orders", examples=[{"id": "ORD-001", "buyer_name": "John Doe", "date": "25-12-2023", "amount": 1500.00, "status": "completed"}])]
    page: Annotated[int, Field(description="Current page number", examples=[1])]
    page_size: Annotated[int, Field(description="Number of orders per page", examples=[10])]
    total: Annotated[int, Field(description="Total number of orders available", examples=[100])]
    total_pages: Annotated[int, Field(description="Total number of pages available", examples=[10])]


class VendorOrdersDashboardResponse(BaseModel):
    total_orders: Annotated[int, Field(description="Total vendor orders", examples=[120])]
    completed_orders: Annotated[int, Field(description="Number of completed orders", examples=[80])]
    pending_orders: Annotated[int, Field(description="Number of pending orders", examples=[30])]
    processing_orders: Annotated[int, Field(description="Number of orders being processed", examples=[10])]
    orders: Annotated[PaginatedOrders, Field(description="Paginated order data", examples={"items": [{"id": "ORD-001", "buyer_name": "John Doe", "date": "25-12-2023", "amount": 1500.00, "status": "completed"}], "page": 1, "page_size": 10, "total": 100, "total_pages": 10})]



class VendorCustomerItem(BaseModel):
    name: Annotated[str, Field(description="Customer's name", examples=["Jane Smith"])]
    email: Annotated[str, Field(description="Customer's email address", examples=["jane.smith@example.com"])]
    total_orders: Annotated[int, Field(description="Total number of orders by this customer", examples=[5])]
    total_spent: Annotated[float, Field(description="Total amount spent by this customer", examples=[7500.00])]


class PaginatedCustomers(BaseModel):
    items: Annotated[list[VendorCustomerItem], Field(description="List of paginated customers", examples=[{"name": "Jane Smith", "email": "jane.smith@example.com", "total_orders": 5, "total_spent": 7500.00}])]
    page: Annotated[int, Field(description="Current page number", examples=[1])]
    page_size: Annotated[int, Field(description="Number of records per page", examples=[10])]
    total: Annotated[int, Field(description="Total number of customers", examples=[100])]
    total_pages: Annotated[int, Field(description="Total pages available", examples=[10])]


class VendorCustomersDashboardResponse(BaseModel):
    customers: Annotated[PaginatedCustomers, Field(description="Paginated customer data", examples={"items": [{"name": "Jane Smith", "email": "jane.smith@example.com", "total_orders": 5, "total_spent": 7500.00}], "page": 1, "page_size": 10, "total": 100, "total_pages": 10})]


class OverviewDashboardResponse(BaseModel):
    total_revenue: Annotated[float, Field(description="Total revenue generated", examples=[15000.75])]
    total_orders: Annotated[int, Field(description="Total number of orders", examples=[120])]
    total_customers: Annotated[int, Field(description="Total number of customers", examples=[85])]
    avg_order_value: Annotated[float, Field(description="Average value of orders", examples=[125.50])]
    revenue_change_percent: Annotated[float, Field(description="Percentage change in revenue", examples=[12.5])]
    orders_change_percent: Annotated[float, Field(description="Percentage change in orders", examples=[8.2])]
    customers_change_percent: Annotated[float, Field(description="Percentage change in customers", examples=[15.3])]
    recent_orders: Annotated[list[RecentOrder], Field(description="List of recent orders", examples=[{"order_id": "52fecfe4-c101-4d24-9f82-8d66f145dd1d", "customer_name": "John Doe"}])]
    top_products: Annotated[list[TopProduct], Field(description="List of top products", examples=[{"name": "Product A", "sales": 44, "revenue": 4400.00}])]
