from typing import Annotated, Optional

from pydantic import BaseModel, Field


class RecentOrder(BaseModel):
    order_id: Annotated[
        str,
        Field(
            description="Unique identifier for the order",
            examples=["52fecfe4-c101-4d24-9f82-8d66f145dd1d"],
        ),
    ]
    customer_name: Annotated[
        str,
        Field(
            description="Name of the customer who placed the order",
            examples=["John Doe"],
        ),
    ]
    amount: Annotated[
        float,
        Field(description="Total amount for the order", examples=[250.50]),
    ]
    status: Annotated[
        str,
        Field(description="Current status of the order", examples=["delivered"]),
    ]


class TopProduct(BaseModel):
    name: Annotated[
        str, Field(description="Name of the product", examples=["Product A"])
    ]
    sales: Annotated[
        int, Field(description="Total sales of the product", examples=[44])
    ]
    revenue: Annotated[
        float,
        Field(
            description="Total revenue generated by the product",
            examples=[4400.00],
        ),
    ]


class WithdrawalItem(BaseModel):
    id: Annotated[int, Field(description="Unique transaction ID", examples=[1])]
    description: Annotated[
        str,
        Field(
            description="Description of the withdrawal",
            examples=["Withdrawal to bank account"],
        ),
    ]
    status: Annotated[
        str,
        Field(
            description="Transaction status",
            examples=["completed"],
        ),
    ]
    amount: Annotated[
        float,
        Field(
            description="Negative value representing withdrawn amount",
            examples=[-1500.00],
        ),
    ]
    date: Annotated[
        Optional[str],
        Field(
            None,
            description="Formatted transaction date",
            examples=["2025-04-01 10:30:00"],
        ),
    ]


class WithdrawalHistory(BaseModel):
    items: Annotated[
        list[WithdrawalItem],
        Field(
            description="List of withdrawal transactions",
            examples=[
                [
                    {
                        "id": 1,
                        "description": "Withdrawal to bank account",
                        "status": "completed",
                        "amount": -1500.00,
                        "date": "2025-04-01 10:30:00",
                    }
                ]
            ],
        ),
    ]
    page: Annotated[int, Field(description="Current page number", examples=[1])]
    page_size: Annotated[int, Field(description="Items per page", examples=[10])]
    total: Annotated[
        int,
        Field(description="Total withdrawal count", examples=[50]),
    ]
    total_pages: Annotated[int, Field(description="Total pages", examples=[5])]


class WalletDashboardResponse(BaseModel):
    available_balance: Annotated[
        float,
        Field(description="Available funds", examples=[5000.00]),
    ]
    pending_balance: Annotated[
        float,
        Field(description="Pending funds", examples=[2000.00]),
    ]
    withdrawable_balance: Annotated[
        float,
        Field(description="Funds that can be withdrawn", examples=[3000.00]),
    ]
    withdrawal_history: Annotated[
        WithdrawalHistory,
        Field(
            description="Paginated withdrawal history",
            examples=[
                {
                    "items": [
                        {
                            "id": 1,
                            "description": "Withdrawal to bank account",
                            "status": "completed",
                            "amount": -1500.00,
                            "date": "2025-04-01 10:30:00",
                        }
                    ],
                    "page": 1,
                    "page_size": 10,
                    "total": 50,
                    "total_pages": 5,
                }
            ],
        ),
    ]


class VendorOrderItem(BaseModel):
    id: Annotated[str, Field(description="Order ID", examples=["ORD-001"])]
    buyer_name: Annotated[str, Field(description="Buyer name", examples=["John Doe"])]
    date: Annotated[
        Optional[str],
        Field(None, description="Order date", examples=["25-12-2023"]),
    ]
    amount: Annotated[float, Field(description="Order total", examples=[1500.00])]
    status: Annotated[
        str,
        Field(description="Order status", examples=["completed"]),
    ]


class PaginatedOrders(BaseModel):
    items: Annotated[
        list[VendorOrderItem],
        Field(
            description="Paginated orders",
            examples=[
                [
                    {
                        "id": "ORD-001",
                        "buyer_name": "John Doe",
                        "date": "25-12-2023",
                        "amount": 1500.00,
                        "status": "completed",
                    }
                ]
            ],
        ),
    ]
    page: Annotated[int, Field(description="Page number", examples=[1])]
    page_size: Annotated[int, Field(description="Items per page", examples=[10])]
    total: Annotated[int, Field(description="Total orders", examples=[100])]
    total_pages: Annotated[int, Field(description="Pages", examples=[10])]


class VendorOrdersDashboardResponse(BaseModel):
    total_orders: Annotated[int, Field(examples=[120])]
    completed_orders: Annotated[int, Field(examples=[80])]
    pending_orders: Annotated[int, Field(examples=[30])]
    processing_orders: Annotated[int, Field(examples=[10])]
    orders: Annotated[
        PaginatedOrders,
        Field(description="Paginated data"),
    ]


class VendorCustomerItem(BaseModel):
    name: Annotated[str, Field(examples=["Jane Smith"])]
    email: Annotated[str, Field(examples=["jane.smith@example.com"])]
    total_orders: Annotated[int, Field(examples=[5])]
    total_spent: Annotated[float, Field(examples=[7500.00])]


class PaginatedCustomers(BaseModel):
    items: Annotated[
        list[VendorCustomerItem],
        Field(
            examples=[
                [
                    {
                        "name": "Jane Smith",
                        "email": "jane.smith@example.com",
                        "total_orders": 5,
                        "total_spent": 7500.00,
                    }
                ]
            ],
        ),
    ]
    page: Annotated[int, Field(examples=[1])]
    page_size: Annotated[int, Field(examples=[10])]
    total: Annotated[int, Field(examples=[100])]
    total_pages: Annotated[int, Field(examples=[10])]


class VendorCustomersDashboardResponse(BaseModel):
    customers: PaginatedCustomers


class OverviewDashboardResponse(BaseModel):
    total_revenue: Annotated[float, Field(examples=[15000.75])]
    total_orders: Annotated[int, Field(examples=[120])]
    total_customers: Annotated[int, Field(examples=[85])]
    avg_order_value: Annotated[float, Field(examples=[125.50])]
    revenue_change_percent: Annotated[float, Field(examples=[12.5])]
    orders_change_percent: Annotated[float, Field(examples=[8.2])]
    customers_change_percent: Annotated[float, Field(examples=[15.3])]
    avg_order_value_change_percent: Annotated[float, Field(examples=[5.0])]
    recent_orders: Annotated[
        list[RecentOrder],
        Field(
            examples=[
                [
                    {
                        "order_id": "52fecfe4-c101-4d24-9f82-8d66f145dd1d",
                        "customer_name": "John Doe",
                        "amount": 250.5,
                        "status": "delivered",
                    }
                ]
            ],
        ),
    ]
    top_products: Annotated[
        list[TopProduct],
        Field(
            examples=[[{"name": "Product A", "sales": 44, "revenue": 4400.00}]],
        ),
    ]
