"""Optimization of suborder db

Revision ID: 0075b01f8e86
Revises: d88bfc3f3121
Create Date: 2026-01-07 01:46:02.837999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0075b01f8e86'
down_revision: Union[str, Sequence[str], None] = 'd88bfc3f3121'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suborder_snapshots',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('total_customers', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'snapshot_time', name='uix_store_snapshot_time')
    )
    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_snapshot_time'), ['snapshot_time'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_snapshot_time'))
    
    op.execute("DROP TRIGGER IF EXISTS trg_update_suborder_snapshot ON suborders")
    op.execute("DROP FUNCTION IF EXISTS update_suborder_snapshot()")

    op.drop_table('suborder_snapshots')
    
    # ### end Alembic commands ###
