"""Not null

Revision ID: 061687c6dc2a
Revises: f0fc34f9542f
Create Date: 2026-07-21 13:13:08.565506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061687c6dc2a'
down_revision: Union[str, Sequence[str], None] = 'f0fc34f9542f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Manually create the missing custom PostgreSQL enums before tables use them
    order_item_status = postgresql.ENUM('pending', 'accepted', 'declined', name='order_item_status_enum')
    order_item_status.create(op.get_bind(), checkfirst=True)

    order_status = postgresql.ENUM('initiated', 'failed', 'cancelled', 'declined', 'paid', 'abandoned', 'accepted', 'out_for_delivery', 'delivered', name='order_status_enum')
    order_status.create(op.get_bind(), checkfirst=True)

    payment_status = postgresql.ENUM('successful', 'cancelled', 'initiated', 'declined', 'refunded', 'abandoned', 'failed', name='payment_status_enum')
    payment_status.create(op.get_bind(), checkfirst=True)

    suborder_status = postgresql.ENUM('pending', 'paid', 'accepted', 'declined', 'shipped', 'delivered', 'cancelled', name='suborder_status_enum')
    suborder_status.create(op.get_bind(), checkfirst=True)

    # 2. Fix the initial problem by making the link column nullable
    with op.batch_alter_table('outing_events', schema=None) as batch_op:
        batch_op.alter_column('link', existing_type=sa.String(), nullable=True)

    # 3. Process autogenerated schema synchronization rules
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_a_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_user_b_id'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'accepted', 'declined', name='order_item_status_enum'), nullable=False))
        batch_op.alter_column('product_snapshot',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('products', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
        batch_op.add_column(sa.Column('idempotent_key', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('reference_token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('initiated', 'failed', 'cancelled', 'declined', 'paid', 'abandoned', 'accepted', 'out_for_delivery', 'delivered', name='order_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('track_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.alter_column('total_amount',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['reference_token'])
        batch_op.create_unique_constraint(None, ['idempotent_key'])
        batch_op.create_unique_constraint(None, ['track_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.Enum('successful', 'cancelled', 'initiated', 'declined', 'refunded', 'abandoned', 'failed', name='payment_status_enum'), nullable=False))

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_user_device'), type_='unique')
        batch_op.create_unique_constraint('uix_refresh_tokens_user_id_device_id', ['user_id', 'device_id'])

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'order_items', ['order_item_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('shipment_info', schema=None) as batch_op:
        batch_op.alter_column('delivery_fee',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False,
               postgresql_using="NULLIF(delivery_fee, '')::double precision")

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('store_logo',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="NULLIF(store_logo, '')::json")
        batch_op.alter_column('store_banner',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True,
               postgresql_using="NULLIF(store_banner, '')::json")

    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('suborders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('pending', 'paid', 'accepted', 'declined', 'shipped', 'delivered', 'cancelled', name='suborder_status_enum'), nullable=False))
        batch_op.add_column(sa.Column('track_id', sa.String(), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['track_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'admin', 'vendor', name='user_role_enum'),
               nullable=False)

    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('pending_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('withdrawable_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('withdrawable_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('pending_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'admin', 'vendor', name='user_role_enum'),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('suborders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('track_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('store_banner',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('store_logo',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('shipment_info', schema=None) as batch_op:
        batch_op.alter_column('delivery_fee',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uix_refresh_tokens_user_id_device_id', type_='unique')
        batch_op.create_unique_constraint('uix_user_device', ['user_id', 'device_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('payment_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('track_id')
        batch_op.drop_column('status')
        batch_op.drop_column('reference_token')
        batch_op.drop_column('idempotent_key')
        batch_op.drop_column('products')


    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=postgresql.JSON(astext_type=sa.Text()),
                existing_nullable=False)
        batch_op.drop_column('status')

        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.drop_column('payload')
        
        with op.batch_alter_table('conversations', schema=None) as batch_op:
            batch_op.create_index('ix_conversations_user_b_id', ['user_b_id'], unique=False)
        batch_op.create_index('ix_conversations_user_a_id', ['user_a_id'], unique=False)

        with op.batch_alter_table('outing_events', schema=None) as batch_op:
            batch_op.alter_column('link', existing_type=sa.String(), nullable=False)

        postgresql.ENUM(name='order_item_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='order_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='payment_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='suborder_status_enum').drop(op.get_bind(), checkfirst=True)