"""Not null

Revision ID: 061687c6dc2a
Revises: f0fc34f9542f
Create Date: 2026-07-21 13:13:08.565506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '061687c6dc2a'
down_revision: Union[str, Sequence[str], None] = 'd47b2c1a8e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def _column_exists(table_name: str, column_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    inspector = sa.inspect(op.get_bind())
    return any(column["name"] == column_name for column in inspector.get_columns(table_name))


def _column_type(table_name: str, column_name: str) -> object | None:
    if not _column_exists(table_name, column_name):
        return None
    inspector = sa.inspect(op.get_bind())
    for column in inspector.get_columns(table_name):
        if column["name"] == column_name:
            return column["type"]
    return None


def _is_string_type(column_type: object | None) -> bool:
    return isinstance(column_type, (sa.String, sa.Text))


def _index_exists(table_name: str, index_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    inspector = sa.inspect(op.get_bind())
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    if not _table_exists(table_name):
        return False
    bind = op.get_bind()
    schema = bind.dialect.default_schema_name
    return (
        bind.execute(
            sa.text(
                """
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = :schema
                  AND t.relname = :table_name
                  AND c.conname = :constraint_name
                LIMIT 1
                """
            ),
            {
                "schema": schema,
                "table_name": table_name,
                "constraint_name": constraint_name,
            },
        ).first()
        is not None
    )


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Manually create the missing custom PostgreSQL enums before tables use them
    order_item_status = postgresql.ENUM('pending', 'accepted', 'declined', name='order_item_status_enum')
    order_item_status.create(op.get_bind(), checkfirst=True)

    order_status = postgresql.ENUM('initiated', 'failed', 'cancelled', 'declined', 'paid', 'abandoned', 'accepted', 'out_for_delivery', 'delivered', name='order_status_enum')
    order_status.create(op.get_bind(), checkfirst=True)

    payment_status = postgresql.ENUM('successful', 'cancelled', 'initiated', 'declined', 'refunded', 'abandoned', 'failed', name='payment_status_enum')
    payment_status.create(op.get_bind(), checkfirst=True)

    suborder_status = postgresql.ENUM('pending', 'paid', 'accepted', 'declined', 'shipped', 'delivered', 'cancelled', name='suborder_status_enum')
    suborder_status.create(op.get_bind(), checkfirst=True)

    # 2. Fix the initial problem by making the link column nullable
    with op.batch_alter_table('outing_events', schema=None) as batch_op:
        batch_op.alter_column('link', existing_type=sa.String(), nullable=True)

    # 3. Process autogenerated schema synchronization rules
    inspector = sa.inspect(op.get_bind())
    if inspector.has_table("conversations"):
        existing_indexes = {index["name"] for index in inspector.get_indexes("conversations")}
        with op.batch_alter_table("conversations", schema=None) as batch_op:
            if batch_op.f("ix_conversations_user_a_id") in existing_indexes:
                batch_op.drop_index(batch_op.f("ix_conversations_user_a_id"))
            if batch_op.f("ix_conversations_user_b_id") in existing_indexes:
                batch_op.drop_index(batch_op.f("ix_conversations_user_b_id"))

    if inspector.has_table("notifications"):
        notification_columns = {
            column["name"] for column in inspector.get_columns("notifications")
        }
        with op.batch_alter_table("notifications", schema=None) as batch_op:
            if "payload" not in notification_columns:
                batch_op.add_column(
                    sa.Column(
                        "payload",
                        postgresql.JSONB(astext_type=sa.Text()),
                        nullable=True,
                    )
                )

    if inspector.has_table("order_items"):
        order_item_columns = {
            column["name"] for column in inspector.get_columns("order_items")
        }
        with op.batch_alter_table("order_items", schema=None) as batch_op:
            if "status" not in order_item_columns:
                batch_op.add_column(
                    sa.Column(
                        "status",
                        sa.Enum(
                            "pending",
                            "accepted",
                            "declined",
                            name="order_item_status_enum",
                        ),
                        nullable=False,
                    )
                )
            if "product_snapshot" in order_item_columns:
                batch_op.alter_column(
                    "product_snapshot",
                    existing_type=postgresql.JSON(astext_type=sa.Text()),
                    type_=postgresql.JSONB(astext_type=sa.Text()),
                    existing_nullable=False,
                )

    if inspector.has_table("orders"):
        order_columns = {column["name"] for column in inspector.get_columns("orders")}
        with op.batch_alter_table("orders", schema=None) as batch_op:
            if "products" not in order_columns:
                batch_op.add_column(
                    sa.Column(
                        "products",
                        postgresql.JSONB(astext_type=sa.Text()),
                        server_default="[]",
                        nullable=False,
                    )
                )
            if "idempotent_key" not in order_columns:
                batch_op.add_column(sa.Column("idempotent_key", sa.String(), nullable=False))
            if "reference_token" not in order_columns:
                batch_op.add_column(sa.Column("reference_token", sa.String(), nullable=False))
            if "status" not in order_columns:
                batch_op.add_column(
                    sa.Column(
                        "status",
                        sa.Enum(
                            "initiated",
                            "failed",
                            "cancelled",
                            "declined",
                            "paid",
                            "abandoned",
                            "accepted",
                            "out_for_delivery",
                            "delivered",
                            name="order_status_enum",
                        ),
                        nullable=False,
                    )
                )
            if "track_id" not in order_columns:
                batch_op.add_column(sa.Column("track_id", sa.String(), nullable=False))
            if "username" not in order_columns:
                batch_op.add_column(sa.Column("username", sa.String(), nullable=False))
            if "total_amount" in order_columns:
                batch_op.alter_column(
                    "total_amount",
                    existing_type=sa.INTEGER(),
                    type_=sa.Float(),
                    existing_nullable=False,
                )
            if _constraint_exists("orders", "orders_reference_token_key") is False and "reference_token" in order_columns:
                batch_op.create_unique_constraint(None, ["reference_token"])
            if _constraint_exists("orders", "orders_idempotent_key_key") is False and "idempotent_key" in order_columns:
                batch_op.create_unique_constraint(None, ["idempotent_key"])
            if _constraint_exists("orders", "orders_track_id_key") is False and "track_id" in order_columns:
                batch_op.create_unique_constraint(None, ["track_id"])

    if inspector.has_table("payments"):
        payment_columns = {
            column["name"] for column in inspector.get_columns("payments")
        }
        with op.batch_alter_table("payments", schema=None) as batch_op:
            if "payment_url" not in payment_columns:
                batch_op.add_column(sa.Column("payment_url", sa.String(), nullable=False))
            if "status" not in payment_columns:
                batch_op.add_column(
                    sa.Column(
                        "status",
                        sa.Enum(
                            "successful",
                            "cancelled",
                            "initiated",
                            "declined",
                            "refunded",
                            "abandoned",
                            "failed",
                            name="payment_status_enum",
                        ),
                        nullable=False,
                    )
                )

    if inspector.has_table("refresh_tokens"):
        with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
            if _constraint_exists("refresh_tokens", "uix_user_device"):
                batch_op.drop_constraint(batch_op.f("uix_user_device"), type_="unique")
            if not _constraint_exists(
                "refresh_tokens", "uix_refresh_tokens_user_id_device_id"
            ):
                batch_op.create_unique_constraint(
                    "uix_refresh_tokens_user_id_device_id", ["user_id", "device_id"]
                )

    if inspector.has_table("refunds"):
        with op.batch_alter_table("refunds", schema=None) as batch_op:
            if not _constraint_exists("refunds", "refunds_order_item_id_fkey"):
                batch_op.create_foreign_key(
                    None, "order_items", ["order_item_id"], ["id"], ondelete="SET NULL"
                )

    shipment_delivery_fee_type = _column_type("shipment_info", "delivery_fee")
    if _is_string_type(shipment_delivery_fee_type):
        with op.batch_alter_table("shipment_info", schema=None) as batch_op:
            batch_op.alter_column(
                "delivery_fee",
                existing_type=sa.VARCHAR(),
                type_=sa.Float(),
                existing_nullable=False,
                postgresql_using=(
                    "CASE "
                    "WHEN btrim(delivery_fee::text) = '' THEN NULL "
                    "ELSE btrim(delivery_fee::text)::double precision "
                    "END"
                ),
            )

    if inspector.has_table("stores"):
        with op.batch_alter_table("stores", schema=None) as batch_op:
            if _is_string_type(_column_type("stores", "store_logo")):
                batch_op.alter_column(
                    "store_logo",
                    existing_type=sa.VARCHAR(),
                    type_=sa.JSON(),
                    existing_nullable=True,
                    postgresql_using=(
                        "CASE "
                        "WHEN btrim(store_logo::text) = '' THEN NULL "
                        "ELSE btrim(store_logo::text)::json "
                        "END"
                    ),
                )
            if _is_string_type(_column_type("stores", "store_banner")):
                batch_op.alter_column(
                    "store_banner",
                    existing_type=sa.VARCHAR(),
                    type_=sa.JSON(),
                    existing_nullable=True,
                    postgresql_using=(
                        "CASE "
                        "WHEN btrim(store_banner::text) = '' THEN NULL "
                        "ELSE btrim(store_banner::text)::json "
                        "END"
                    ),
                )

    if inspector.has_table("suborder_snapshots"):
        with op.batch_alter_table("suborder_snapshots", schema=None) as batch_op:
            if not _constraint_exists("suborder_snapshots", "suborder_snapshots_store_id_fkey"):
                batch_op.create_foreign_key(
                    None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
                )

    if inspector.has_table("suborders"):
        suborder_columns = {column["name"] for column in inspector.get_columns("suborders")}
        with op.batch_alter_table("suborders", schema=None) as batch_op:
            if "status" not in suborder_columns:
                batch_op.add_column(
                    sa.Column(
                        "status",
                        sa.Enum(
                            "pending",
                            "paid",
                            "accepted",
                            "declined",
                            "shipped",
                            "delivered",
                            "cancelled",
                            name="suborder_status_enum",
                        ),
                        nullable=False,
                    )
                )
            if "track_id" not in suborder_columns:
                batch_op.add_column(sa.Column("track_id", sa.String(), nullable=False))
            if "username" in suborder_columns:
                batch_op.alter_column(
                    "username",
                    existing_type=sa.VARCHAR(),
                    nullable=False,
                )
            if _constraint_exists("suborders", "suborders_track_id_key") is False and "track_id" in suborder_columns:
                batch_op.create_unique_constraint(None, ["track_id"])

    if inspector.has_table("users"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            if _column_exists("users", "is_active"):
                batch_op.alter_column(
                    "is_active",
                    existing_type=sa.BOOLEAN(),
                    nullable=False,
                )
            if _column_exists("users", "role"):
                batch_op.alter_column(
                    "role",
                    existing_type=postgresql.ENUM(
                        "user", "admin", "vendor", name="user_role_enum"
                    ),
                    nullable=False,
                )

    if inspector.has_table("wallets"):
        with op.batch_alter_table("wallets", schema=None) as batch_op:
            if _column_exists("wallets", "available_balance"):
                batch_op.alter_column(
                    "available_balance",
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False,
                )
            if _column_exists("wallets", "pending_balance"):
                batch_op.alter_column(
                    "pending_balance",
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False,
                )
            if _column_exists("wallets", "withdrawable_balance"):
                batch_op.alter_column(
                    "withdrawable_balance",
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False,
                )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('wallets', schema=None) as batch_op:
        batch_op.alter_column('withdrawable_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('pending_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('available_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=postgresql.ENUM('user', 'admin', 'vendor', name='user_role_enum'),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('suborders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('track_id')
        batch_op.drop_column('status')

    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.alter_column('store_banner',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.alter_column('store_logo',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    with op.batch_alter_table('shipment_info', schema=None) as batch_op:
        batch_op.alter_column('delivery_fee',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint('uix_refresh_tokens_user_id_device_id', type_='unique')
        batch_op.create_unique_constraint('uix_user_device', ['user_id', 'device_id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('payment_url')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('username')
        batch_op.drop_column('track_id')
        batch_op.drop_column('status')
        batch_op.drop_column('reference_token')
        batch_op.drop_column('idempotent_key')
        batch_op.drop_column('products')


    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.alter_column('product_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
                type_=postgresql.JSON(astext_type=sa.Text()),
                existing_nullable=False)
        batch_op.drop_column('status')

        inspector = sa.inspect(op.get_bind())
        if inspector.has_table("notifications"):
            notification_columns = {
                column["name"] for column in inspector.get_columns("notifications")
            }
            with op.batch_alter_table("notifications", schema=None) as batch_op:
                if "payload" in notification_columns:
                    batch_op.drop_column("payload")
        
        inspector = sa.inspect(op.get_bind())
        if inspector.has_table("conversations"):
            with op.batch_alter_table("conversations", schema=None) as batch_op:
                existing_indexes = {index["name"] for index in inspector.get_indexes("conversations")}
                if batch_op.f("ix_conversations_user_b_id") not in existing_indexes:
                    batch_op.create_index("ix_conversations_user_b_id", ["user_b_id"], unique=False)
                if batch_op.f("ix_conversations_user_a_id") not in existing_indexes:
                    batch_op.create_index("ix_conversations_user_a_id", ["user_a_id"], unique=False)

        with op.batch_alter_table('outing_events', schema=None) as batch_op:
            batch_op.alter_column('link', existing_type=sa.String(), nullable=False)

        postgresql.ENUM(name='order_item_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='order_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='payment_status_enum').drop(op.get_bind(), checkfirst=True)
        postgresql.ENUM(name='suborder_status_enum').drop(op.get_bind(), checkfirst=True)
