"""remove unique constraint on device_id and add unique contraint on user_id and device_id

Revision ID: 06a6b87f1747
Revises: 52ce096d0c9d
Create Date: 2026-03-21 05:09:23.811042

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06a6b87f1747"
down_revision: Union[str, Sequence[str], None] = "52ce096d0c9d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("refresh_tokens_device_id_key"), type_="unique"
        )
        batch_op.create_unique_constraint("uix_user_device", ["user_id", "device_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("uix_user_device", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("refresh_tokens_device_id_key"),
            ["device_id"],
            postgresql_nulls_not_distinct=False,
        )

    # ### end Alembic commands ###
