"""create matching, matching_request, notification and user_block models

Revision ID: 08893a1effb9
Revises: 4d70fb1ea2c6
Create Date: 2026-04-30 12:29:31.039762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08893a1effb9'
down_revision: Union[str, Sequence[str], None] = '4d70fb1ea2c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
