"""add products column to order and updated order status enum

Revision ID: 09b07077a188
Revises: 7580a28ee02c
Create Date: 2025-11-25 12:27:56.389481

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "09b07077a188"
down_revision: Union[str, Sequence[str], None] = "7580a28ee02c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "products", postgresql.JSONB(astext_type=sa.Text()), nullable=False
            )
        )

    op.execute("DROP TYPE order_status_enum CASCADE")
    op.execute("DROP TYPE payment_status_enum CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("products")

    # ### end Alembic commands ###
