"""empty message

Revision ID: 1a3fbb4c3478
Revises: e03090a3d31d
Create Date: 2026-03-08 22:28:43.286342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3fbb4c3478'
down_revision: Union[str, Sequence[str], None] = 'e03090a3d31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


order_item_status_enum = sa.Enum(
    'pending',
    'accepted',
    'declined',
    name='order_item_status_enum'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    order_item_status_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'status',
                order_item_status_enum,
                nullable=False,
                server_default='pending'
            )
        )

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['track_id'])

    with op.batch_alter_table('suborders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_id', sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ['track_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suborders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('track_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('track_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
