"""empty message

Revision ID: 1a3fbb4c3478
Revises: e03090a3d31d
Create Date: 2026-03-08 22:28:43.286342

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a3fbb4c3478"
down_revision: Union[str, Sequence[str], None] = "e03090a3d31d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


order_item_status_enum = sa.Enum(
    "pending", "accepted", "declined", name="order_item_status_enum"
)


def _column_exists(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def _unique_on_column_exists(table_name: str, column_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    for unique in inspector.get_unique_constraints(table_name):
        cols = unique.get("column_names") or []
        if column_name in cols:
            return True
    return False


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (
        _table_exists("order_items")
        and _table_exists("orders")
        and _table_exists("suborders")
    ):
        return
    order_item_status_enum.create(op.get_bind(), checkfirst=True)

    if not _column_exists("order_items", "status"):
        with op.batch_alter_table("order_items", schema=None) as batch_op:
            batch_op.add_column(
                sa.Column(
                    "status",
                    order_item_status_enum,
                    nullable=False,
                    server_default="pending",
                )
            )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        if not _column_exists("orders", "track_id"):
            batch_op.add_column(sa.Column("track_id", sa.String(), nullable=False))
        if not _unique_on_column_exists("orders", "track_id"):
            batch_op.create_unique_constraint(None, ["track_id"])

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        if not _column_exists("suborders", "track_id"):
            batch_op.add_column(sa.Column("track_id", sa.String(), nullable=False))
        if not _unique_on_column_exists("suborders", "track_id"):
            batch_op.create_unique_constraint(None, ["track_id"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (
        _table_exists("order_items")
        and _table_exists("orders")
        and _table_exists("suborders")
    ):
        return
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("track_id")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("track_id")

    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
