"""convert all models to use sqlalchemy v2 format

Revision ID: 21f8566207fc
Revises: b838baf21962
Create Date: 2025-12-22 03:26:53.169441

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "21f8566207fc"
down_revision: Union[str, Sequence[str], None] = "b838baf21962"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    required_tables = {"orders", "payments", "suborders", "users", "wallets"}
    if not required_tables.issubset(
        {table for table in required_tables if _table_exists(table)}
    ):
        return
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "initiated",
                "failed",
                "cancelled",
                "declined",
                "paid",
                "abandoned",
                "accepted",
                "out_for_delivery",
                "delivered",
                name="order_status_enum",
            ),
            nullable=False,
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "successful",
                "cancelled",
                "initiated",
                "declined",
                "refunded",
                "abandoned",
                "failed",
                name="payment_status_enum",
            ),
            nullable=False,
        )

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.alter_column(
            "shipping_fee", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.alter_column(
            "role",
            existing_type=postgresql.ENUM(
                "user", "admin", "vendor", name="user_role_enum"
            ),
            nullable=False,
        )

    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.alter_column(
            "available_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "pending_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )
        batch_op.alter_column(
            "withdrawable_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    required_tables = {"orders", "payments", "suborders", "users", "wallets"}
    if not required_tables.issubset(
        {table for table in required_tables if _table_exists(table)}
    ):
        return
    with op.batch_alter_table("wallets", schema=None) as batch_op:
        batch_op.alter_column(
            "withdrawable_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "pending_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )
        batch_op.alter_column(
            "available_balance",
            existing_type=sa.DOUBLE_PRECISION(precision=53),
            nullable=True,
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "role",
            existing_type=postgresql.ENUM(
                "user", "admin", "vendor", name="user_role_enum"
            ),
            nullable=True,
        )
        batch_op.alter_column("is_active", existing_type=sa.BOOLEAN(), nullable=True)

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.alter_column("shipping_fee", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "successful",
                "cancelled",
                "initiated",
                "declined",
                "refunded",
                "abandoned",
                "failed",
                name="payment_status_enum",
            ),
            nullable=True,
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=postgresql.ENUM(
                "initiated",
                "failed",
                "cancelled",
                "declined",
                "paid",
                "abandoned",
                "accepted",
                "out_for_delivery",
                "delivered",
                name="order_status_enum",
            ),
            nullable=True,
        )

    # ### end Alembic commands ###
