"""create newsletter table

Revision ID: 24eddf7b8fa2
Revises: fb1a4c09a912
Create Date: 2026-04-22 10:46:46.737994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24eddf7b8fa2'
down_revision: Union[str, Sequence[str], None] = 'fb1a4c09a912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
