"""Model Fix

Revision ID: 27a777c35db5
Revises: d1ec4d316d2f
Create Date: 2025-10-01 14:25:40.559978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27a777c35db5'
down_revision: Union[str, Sequence[str], None] = 'd1ec4d316d2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts_info',
    sa.Column('account_name', sa.String(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payouts')
    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=False))
        batch_op.drop_column('phone')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('orders_payment_id_fkey'), type_='foreignkey')
        batch_op.drop_column('payment_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.UUID(), nullable=False))
        batch_op.create_foreign_key(None, 'orders', ['order_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('order_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('orders_payment_id_fkey'), 'users', ['payment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contact_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('phone_number')

    op.create_table('payouts',
    sa.Column('account_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('bank_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('payouts_store_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('payouts_pkey'))
    )
    op.drop_table('payouts_info')
    # ### end Alembic commands ###
