"""empty message

Revision ID: 49ab2ce90040
Revises: ff15258a9ee7
Create Date: 2025-11-26 22:03:11.885076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "49ab2ce90040"
down_revision: Union[str, Sequence[str], None] = "ff15258a9ee7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("suborders"):
        return
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.alter_column("shipping_fee", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column("status")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("suborders"):
        return
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                postgresql.ENUM(
                    "pending",
                    "processing",
                    "shipped",
                    "delivered",
                    "cancelled",
                    name="suborder_status_enum",
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.alter_column(
            "shipping_fee", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
