"""Fixed id cycle issue

Revision ID: 4ce3cfcf2a9c
Revises: a390ca81e28e
Create Date: 2025-10-01 14:28:48.787565

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4ce3cfcf2a9c"
down_revision: Union[str, Sequence[str], None] = "a390ca81e28e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("payments_order_id_fkey"), type_="foreignkey"
        )
        batch_op.drop_column("order_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("payments_order_id_fkey"),
            "orders",
            ["order_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###
