"""Phone mnuber issue

Revision ID: 51428e91da4f
Revises: 4ce3cfcf2a9c
Create Date: 2025-10-04 12:26:10.400260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51428e91da4f'
down_revision: Union[str, Sequence[str], None] = '4ce3cfcf2a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_info', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
