"""allembic

Revision ID: 515f208cdc76
Revises: 45affa483b69
Create Date: 2026-04-22 02:12:57.867275

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "515f208cdc76"
down_revision: str | Sequence[str] | None = "45affa483b69"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
