"""change order total amount and shippment delivery fee to float'


Revision ID: 52ce096d0c9d
Revises: 57d5a9be68dc
Create Date: 2026-03-09 00:11:04.927429

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52ce096d0c9d"
down_revision: Union[str, Sequence[str], None] = "57d5a9be68dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (_table_exists("orders") and _table_exists("shipment_info")):
        return
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "total_amount",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            existing_nullable=False,
        )

    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.alter_column(
            "delivery_fee",
            existing_type=sa.VARCHAR(),
            type_=sa.Float(),
            existing_nullable=False,
            postgresql_using="delivery_fee::double precision",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (_table_exists("orders") and _table_exists("shipment_info")):
        return
    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.alter_column(
            "delivery_fee",
            existing_type=sa.Float(),
            type_=sa.VARCHAR(),
            existing_nullable=False,
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column(
            "total_amount",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
