"""added a status column to suborders

Revision ID: 57a8925dbc7e
Revises: 49ab2ce90040
Create Date: 2025-11-26 22:14:39.867284

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57a8925dbc7e"
down_revision: Union[str, Sequence[str], None] = "49ab2ce90040"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("suborders"):
        return
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum(
                    "pending",
                    "paid",
                    "accepted",
                    "declined",
                    "shipped",
                    "delivered",
                    "cancelled",
                    name="suborder_status_enum",
                ),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("suborders"):
        return
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
