"""Removing the implemented Metrics

Revision ID: 7071ee03ddca
Revises: dbd0f66e6475
Create Date: 2025-11-21 00:01:02.416710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7071ee03ddca"
down_revision: Union[str, Sequence[str], None] = "dbd0f66e6475"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=False))

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.alter_column("username", existing_type=sa.VARCHAR(), nullable=True)

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("username")

    # ### end Alembic commands ###
