"""reinitialize the order status and payment status enum

Revision ID: 712b24303135
Revises: 09b07077a188
Create Date: 2025-11-25 12:57:13.302005

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "712b24303135"
down_revision: Union[str, Sequence[str], None] = "09b07077a188"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (_table_exists("orders") and _table_exists("payments")):
        return
    op.execute(
        "CREATE TYPE order_status_enum AS ENUM ('initiated', 'failed', 'cancelled', 'declined', 'paid', 'abandoned', 'accepted', 'out_for_delivery', 'delivered')"
    )
    op.execute(
        "CREATE TYPE payment_status_enum AS ENUM ('successful', 'cancelled', 'initiated', 'declined', 'refunded', 'abandoned', 'failed')"
    )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.Enum(name="order_status_enum"), nullable=True)
        )

    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("status", sa.Enum(name="payment_status_enum"), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not (_table_exists("orders") and _table_exists("payments")):
        return
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("status")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
