"""merge store and store_info tables

Revision ID: 763101b50b76
Revises: 62bfe144ab41
Create Date: 2025-10-29 11:42:55.861484

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "763101b50b76"
down_revision: Union[str, Sequence[str], None] = "62bfe144ab41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "store_info",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("phone_number", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("store_logo", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("store_banner", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("store_description", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.drop_column("store_description")
        batch_op.drop_column("store_banner")
        batch_op.drop_column("store_logo")
        batch_op.drop_column("email")
        batch_op.drop_column("phone_number")
        batch_op.drop_column("address")

    op.drop_table("store_info")
    # ### end Alembic commands ###
