"""changed is_store_owner to not be nullable and has a server default of False

Revision ID: 8001140c8b1d
Revises: 179ac2fbd663
Create Date: 2025-10-28 22:39:29.211722

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8001140c8b1d"
down_revision: Union[str, Sequence[str], None] = "179ac2fbd663"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_store_owner", existing_type=sa.BOOLEAN(), nullable=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "is_store_owner", existing_type=sa.BOOLEAN(), nullable=True
        )

    # ### end Alembic commands ###
