"""add vendor enum to user_role_enum

Revision ID: 805436fe47fe
Revises: e12ae8ecc848
Create Date: 2025-09-18 10:58:27.616841

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "805436fe47fe"
down_revision: Union[str, Sequence[str], None] = "e12ae8ecc848"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE user_role_enum ADD VALUE IF NOT EXISTS 'vendor'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
