"""added payment_url column to payment table

Revision ID: 81c9b04dcc14
Revises: 712b24303135
Create Date: 2025-11-25 17:02:10.887988

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81c9b04dcc14"
down_revision: Union[str, Sequence[str], None] = "712b24303135"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_url", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("payment_url")

    # ### end Alembic commands ###
