"""added payment_url column to payment table

Revision ID: 81c9b04dcc14
Revises: 712b24303135
Create Date: 2025-11-25 17:02:10.887988

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81c9b04dcc14"
down_revision: Union[str, Sequence[str], None] = "712b24303135"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("payments"):
        return
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_url", sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("payments"):
        return
    with op.batch_alter_table("payments", schema=None) as batch_op:
        batch_op.drop_column("payment_url")

    # ### end Alembic commands ###
