"""fields update to suborder and user

Revision ID: 89cfb67b262d
Revises: 5b2acbb6a20d
Create Date: 2025-12-10 02:04:40.409395

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89cfb67b262d"
down_revision: Union[str, Sequence[str], None] = "5b2acbb6a20d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
