"""remove password column from user model

Revision ID: 8a91c8c8b7cd
Revises: 0f85675c415d
Create Date: 2025-09-19 13:08:36.897854

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8a91c8c8b7cd"
down_revision: Union[str, Sequence[str], None] = "0f85675c415d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False)
        )

    # ### end Alembic commands ###
