"""Adding Refund Table and User Wallet

Revision ID: 9f5ffd19a5d4
Revises: 5a8ae401c1a3
Create Date: 2026-01-29 17:16:26.252737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f5ffd19a5d4'
down_revision: Union[str, Sequence[str], None] = '5a8ae401c1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'accepted', 'declined', name='order_item_status_enum').create(op.get_bind())
    sa.Enum('pending', 'released', 'failed', name='refund_status').create(op.get_bind())
    op.create_table('user_wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('pending_balance', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refunds',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('order_item_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'released', 'failed', name='refund_status', create_type=False), nullable=False),
    sa.Column('release_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['user_wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', name='order_item_status_enum', create_type=False), nullable=False))

    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_snapshot_time'))
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_store_id'), ['store_id'], unique=False)
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='CASCADE')

    op.sync_enum_values(
        enum_schema='public',
        enum_name='suborder_status_enum',
        new_values=['pending', 'paid', 'accepted', 'declined', 'shipped', 'delivered', 'cancelled'],
        affected_columns=[TableReference(table_schema='public', table_name='suborders', column_name='status')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_role_enum',
        new_values=['user', 'vendor', 'admin'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='user_role_enum',
        new_values=['user', 'admin', 'vendor'],
        affected_columns=[TableReference(table_schema='public', table_name='users', column_name='role')],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='suborder_status_enum',
        new_values=['pending', 'processing', 'shipped', 'delivered', 'cancelled', 'paid', 'accepted', 'declined'],
        affected_columns=[TableReference(table_schema='public', table_name='suborders', column_name='status')],
        enum_values_to_rename=[],
    )
    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_store_id'))
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_snapshot_time'))
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_snapshot_time'), ['snapshot_time'], unique=True)

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('status')

    op.drop_table('refunds')
    op.drop_table('user_wallets')
    sa.Enum('pending', 'released', 'failed', name='refund_status').drop(op.get_bind())
    sa.Enum('pending', 'accepted', 'declined', name='order_item_status_enum').drop(op.get_bind())
    # ### end Alembic commands ###
