"""Adding Refund Table and User Wallet

Revision ID: 9f5ffd19a5d4
Revises: 5a8ae401c1a3
Create Date: 2026-01-29 17:16:26.252737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f5ffd19a5d4'
down_revision: Union[str, Sequence[str], None] = '5a8ae401c1a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_enum_values(enum_name: str, values: list[str], enum_schema: str = "public") -> None:
    """
    Ensure enum contains all values (best-effort, additive only).

    This avoids requiring the optional `alembic-postgresql-enum` dependency at runtime.
    """
    bind = op.get_bind()
    for value in values:
        bind.execute(
            sa.text(
                f'ALTER TYPE "{enum_schema}"."{enum_name}" ADD VALUE IF NOT EXISTS :value'
            ),
            {"value": value},
        )


def _column_exists(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(col["name"] == column_name for col in inspector.get_columns(table_name))


def _table_exists(table_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'accepted', 'declined', name='order_item_status_enum').create(op.get_bind(), checkfirst=True)
    sa.Enum('pending', 'released', 'failed', name='refund_status').create(op.get_bind(), checkfirst=True)

    if not _table_exists('user_wallets'):
        op.create_table('user_wallets',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False),
        sa.Column('pending_balance', sa.Float(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id')
        )

    if not _table_exists('refunds'):
        op.create_table('refunds',
        sa.Column('wallet_id', sa.UUID(), nullable=False),
        sa.Column('order_item_id', sa.UUID(), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('status', postgresql.ENUM('pending', 'released', 'failed', name='refund_status', create_type=False), nullable=False),
        sa.Column('release_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['wallet_id'], ['user_wallets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )

    if not _column_exists('order_items', 'status'):
        with op.batch_alter_table('order_items', schema=None) as batch_op:
            batch_op.add_column(sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', name='order_item_status_enum', create_type=False), nullable=False))

    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_snapshot_time'))
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_snapshot_time'), ['snapshot_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_store_id'), ['store_id'], unique=False)
        batch_op.create_foreign_key(None, 'stores', ['store_id'], ['id'], ondelete='CASCADE')

    _ensure_enum_values(
        enum_name="suborder_status_enum",
        values=["pending", "paid", "accepted", "declined", "shipped", "delivered", "cancelled"],
    )
    _ensure_enum_values(
        enum_name="user_role_enum",
        values=["user", "vendor", "admin"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enum value removal/reordering isn't safely supported in PostgreSQL; keep additive-only behavior.
    with op.batch_alter_table('suborder_snapshots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_store_id'))
        batch_op.drop_index(batch_op.f('ix_suborder_snapshots_snapshot_time'))
        batch_op.create_index(batch_op.f('ix_suborder_snapshots_snapshot_time'), ['snapshot_time'], unique=True)

    if _column_exists('order_items', 'status'):
        with op.batch_alter_table('order_items', schema=None) as batch_op:
            batch_op.drop_column('status')

    if _table_exists('refunds'):
        op.drop_table('refunds')
    if _table_exists('user_wallets'):
        op.drop_table('user_wallets')
    sa.Enum('pending', 'released', 'failed', name='refund_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum('pending', 'accepted', 'declined', name='order_item_status_enum').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
