"""update outing event model to include location type, token info

Revision ID: a0f44fa24a69
Revises: d8f22e6aaebb
Create Date: 2026-07-16 23:39:11.403650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f44fa24a69'
down_revision: Union[str, Sequence[str], None] = 'd8f22e6aaebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


location_type_enum = postgresql.ENUM(
    "PHYSICAL",
    "VIRTUAL",
    "HYBRID",
    name="location_type_enum",
)
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    location_type_enum.create(bind, checkfirst=True)
    
    op.drop_table('outing_event_interests')
    with op.batch_alter_table('outing_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_type', location_type_enum, nullable=False))
        batch_op.add_column(sa.Column('ticket_info', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('interests', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('creator_id', sa.UUID(as_uuid=False), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['creator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outing_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('creator_id')
        batch_op.drop_column('interests')
        batch_op.drop_column('ticket_info')
        batch_op.drop_column('location_type')

    op.create_table('outing_event_interests',
    sa.Column('outing_event_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('outing_event_interests_interest_id_fkey')),
    sa.ForeignKeyConstraint(['outing_event_id'], ['outing_events.id'], name=op.f('outing_event_interests_outing_event_id_fkey')),
    sa.PrimaryKeyConstraint('outing_event_id', 'interest_id', name=op.f('outing_event_interests_pkey'))
    )
    # ### end Alembic commands ###
