"""Model Fix payments_id in order mistakenly removed

Revision ID: a390ca81e28e
Revises: 27a777c35db5
Create Date: 2025-10-01 14:27:27.013658

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a390ca81e28e"
down_revision: Union[str, Sequence[str], None] = "27a777c35db5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_id", sa.UUID(), nullable=False))
        batch_op.create_foreign_key(
            None, "payments", ["payment_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("payment_id")

    # ### end Alembic commands ###
