"""added is_store_owner to user model

Revision ID: ab80112bf8cf
Revises: c29618a566c3
Create Date: 2025-10-28 21:43:58.562090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ab80112bf8cf"
down_revision: Union[str, Sequence[str], None] = "c29618a566c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "wallets",
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("available_balance", sa.Float(), nullable=True),
        sa.Column("pending_balance", sa.Float(), nullable=True),
        sa.Column("withdrawable_balance", sa.Float(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "wallet_transactions",
        sa.Column("wallet_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum("deposit", "withdrawal", "transfer", name="transaction_type_enum"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "completed", "failed", name="transaction_status_enum"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["wallet_id"], ["wallets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("business_info")
    with op.batch_alter_table("payouts_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("security_question", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("security_answer", sa.String(), nullable=False))
        batch_op.add_column(
            sa.Column("withdrawal_pin", sa.String(length=6), nullable=False)
        )

    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("address", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("phone_number", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("email", sa.String(), nullable=False))
        batch_op.drop_column("store_banner")
        batch_op.drop_column("store_description")

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("username", sa.String(), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_store_owner", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_store_owner")

    with op.batch_alter_table("suborders", schema=None) as batch_op:
        batch_op.drop_column("username")

    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "store_description", sa.VARCHAR(), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("store_banner", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.drop_column("email")
        batch_op.drop_column("phone_number")
        batch_op.drop_column("address")

    with op.batch_alter_table("payouts_info", schema=None) as batch_op:
        batch_op.drop_column("withdrawal_pin")
        batch_op.drop_column("security_answer")
        batch_op.drop_column("security_question")

    op.create_table(
        "business_info",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("address", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("btype", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column("store_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("business_info_store_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("business_info_pkey")),
    )
    op.drop_table("wallet_transactions")
    op.drop_table("wallets")
    # ### end Alembic commands ###
