"""add paid to suborder_enum

Revision ID: af7f3ae39b0d
Revises: 57a8925dbc7e
Create Date: 2025-11-28 17:31:16.405103

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af7f3ae39b0d"
down_revision: Union[str, Sequence[str], None] = "57a8925dbc7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
