"""Added (Store, Order, Payment, OrderItem, SubOrder, Inventory) and Decoupled Business models from user to store

Revision ID: b3c765382398
Revises: 40a0adab966d
Create Date: 2025-09-30 13:27:45.768981

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3c765382398"
down_revision: Union[str, Sequence[str], None] = "40a0adab966d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventories",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("available", sa.Integer(), nullable=False),
        sa.Column("reserved", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("payment_id", sa.UUID(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["payment_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payments",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("provider", sa.String(), server_default="paystack", nullable=False),
        sa.Column("provider_payment_id", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stores",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "suborders",
        sa.Column("order_id", sa.UUID(), nullable=False),
        sa.Column("store_id", sa.UUID(), nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("shipping_fee", sa.Integer(), nullable=False),
        sa.Column("otp", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["store_id"], ["stores.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_items",
        sa.Column("product_id", sa.String(), nullable=False),
        sa.Column("suborder_id", sa.UUID(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("product_snapshot", sa.JSON(), nullable=False),
        sa.Column("unit_price", sa.Integer(), nullable=False),
        sa.Column("line_price", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["suborder_id"], ["suborders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("business_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("business_info_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("contact_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("contact_info_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f("payouts_user_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("shipment_info_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.UUID(), nullable=False))
        batch_op.drop_constraint(
            batch_op.f("store_info_user_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "stores", ["store_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("store_info_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("store_id")

    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("shipment_info_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("store_id")

    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("payouts_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("store_id")

    with op.batch_alter_table("contact_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("contact_info_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("store_id")

    with op.batch_alter_table("business_info", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("business_info_user_id_fkey"),
            "users",
            ["user_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_column("store_id")

    op.drop_table("order_items")
    op.drop_table("suborders")
    op.drop_table("stores")
    op.drop_table("payments")
    op.drop_table("orders")
    op.drop_table("inventories")
    # ### end Alembic commands ###
