"""Fixing alembic

Revision ID: bfa1c30dc407
Revises: 2d1cc668514a
Create Date: 2026-07-14 21:43:21.633296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa1c30dc407'
down_revision: Union[str, Sequence[str], None] = '2d1cc668514a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outing_events',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('banner_url', sa.String(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'LIVE', name='event_state'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_outing_events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outing_event_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['outing_event_id'], ['outing_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'outing_event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_outing_events')
    op.drop_table('outing_events')
    # ### end Alembic commands ###
