"""add is_active column to store

Revision ID: c29618a566c3
Revises: 51428e91da4f
Create Date: 2025-10-06 14:05:56.824042

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c29618a566c3"
down_revision: Union[str, Sequence[str], None] = "51428e91da4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.drop_column("is_active")

    # ### end Alembic commands ###
