"""add outing_event_interest secondary model

Revision ID: d8f22e6aaebb
Revises: bfa1c30dc407
Create Date: 2026-07-16 21:54:33.846455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f22e6aaebb'
down_revision: Union[str, Sequence[str], None] = 'bfa1c30dc407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outing_event_interests',
    sa.Column('outing_event_id', sa.UUID(), nullable=False),
    sa.Column('interest_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['outing_event_id'], ['outing_events.id'], ),
    sa.PrimaryKeyConstraint('outing_event_id', 'interest_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outing_event_interests')
    # ### end Alembic commands ###
