"""convert store_logo and store_banner in store to json

Revision ID: dbd0f66e6475
Revises: 6b0c2f9a7d1a
Create Date: 2025-10-29 14:23:48.013456

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dbd0f66e6475"
down_revision: Union[str, Sequence[str], None] = "6b0c2f9a7d1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("stores"):
        return
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.alter_column(
            "store_logo",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="store_logo::json",
        )
        batch_op.alter_column(
            "store_banner",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            existing_nullable=True,
            postgresql_using="store_banner::json",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.alter_column(
            "store_banner",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "store_logo",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
