"""added otp and otp_time column to user

Revision ID: e12ae8ecc848
Revises: 567c4d0df1fb
Create Date: 2025-09-17 18:34:18.674371

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e12ae8ecc848"
down_revision: Union[str, Sequence[str], None] = "567c4d0df1fb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("business_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_business_info_id"))

    with op.batch_alter_table("contact_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_contact_info_id"))

    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payouts_id"))

    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_shipment_info_id"))

    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_store_info_id"))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("otp", sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column("otp_time", sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_users_id"))

    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_verifications_id"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("verifications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_verifications_id"), ["id"], unique=False)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.drop_column("otp_time")
        batch_op.drop_column("otp")

    with op.batch_alter_table("store_info", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_store_info_id"), ["id"], unique=False)

    with op.batch_alter_table("shipment_info", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_shipment_info_id"), ["id"], unique=False)

    with op.batch_alter_table("payouts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_payouts_id"), ["id"], unique=False)

    with op.batch_alter_table("contact_info", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_contact_info_id"), ["id"], unique=False)

    with op.batch_alter_table("business_info", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_business_info_id"), ["id"], unique=False)

    # ### end Alembic commands ###
