"""added otp and otp_time column to user

Revision ID: e12ae8ecc848
Revises: 567c4d0df1fb
Create Date: 2025-09-17 18:34:18.674371

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e12ae8ecc848"
down_revision: str | Sequence[str] | None = "567c4d0df1fb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _index_exists(table_name: str, index_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(
        index["name"] == index_name for index in inspector.get_indexes(table_name)
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _index_exists("business_info", "ix_business_info_id"):
        with op.batch_alter_table("business_info", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_business_info_id"))

    if _index_exists("contact_info", "ix_contact_info_id"):
        with op.batch_alter_table("contact_info", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_contact_info_id"))

    if _index_exists("payouts", "ix_payouts_id"):
        with op.batch_alter_table("payouts", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_payouts_id"))

    if _index_exists("shipment_info", "ix_shipment_info_id"):
        with op.batch_alter_table("shipment_info", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_shipment_info_id"))

    if _index_exists("store_info", "ix_store_info_id"):
        with op.batch_alter_table("store_info", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_store_info_id"))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("otp", sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column("otp_time", sa.DateTime(), nullable=True))
        if _index_exists("users", "ix_users_id"):
            batch_op.drop_index(batch_op.f("ix_users_id"))

    if _index_exists("verifications", "ix_verifications_id"):
        with op.batch_alter_table("verifications", schema=None) as batch_op:
            batch_op.drop_index(batch_op.f("ix_verifications_id"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _index_exists("verifications", "ix_verifications_id"):
        with op.batch_alter_table("verifications", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_verifications_id"), ["id"], unique=False
            )

    with op.batch_alter_table("users", schema=None) as batch_op:
        if not _index_exists("users", "ix_users_id"):
            batch_op.create_index(batch_op.f("ix_users_id"), ["id"], unique=False)
        batch_op.drop_column("otp_time")
        batch_op.drop_column("otp")

    if not _index_exists("store_info", "ix_store_info_id"):
        with op.batch_alter_table("store_info", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_store_info_id"), ["id"], unique=False)

    if not _index_exists("shipment_info", "ix_shipment_info_id"):
        with op.batch_alter_table("shipment_info", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_shipment_info_id"), ["id"], unique=False
            )

    if not _index_exists("payouts", "ix_payouts_id"):
        with op.batch_alter_table("payouts", schema=None) as batch_op:
            batch_op.create_index(batch_op.f("ix_payouts_id"), ["id"], unique=False)

    if not _index_exists("contact_info", "ix_contact_info_id"):
        with op.batch_alter_table("contact_info", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_contact_info_id"), ["id"], unique=False
            )

    if not _index_exists("business_info", "ix_business_info_id"):
        with op.batch_alter_table("business_info", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_business_info_id"), ["id"], unique=False
            )

    # ### end Alembic commands ###
