"""add bio column to user model

Revision ID: ec695275d4b5
Revises: e315639d45c4
Create Date: 2026-05-20 08:36:13.663021

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec695275d4b5"
down_revision: Union[str, Sequence[str], None] = "e315639d45c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('conversations', schema=None) as batch_op:
    #     batch_op.drop_index(batch_op.f('ix_conversations_user_a_id'))
    #     batch_op.drop_index(batch_op.f('ix_conversations_user_b_id'))

    # with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
    #     batch_op.drop_constraint(batch_op.f('uix_user_device'), type_='unique')
    #     batch_op.create_unique_constraint('uix_refresh_tokens_user_id_device_id', ['user_id', 'device_id'])

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bio", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("bio")

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_constraint("uix_refresh_tokens_user_id_device_id", type_="unique")
        batch_op.create_unique_constraint(
            batch_op.f("uix_user_device"),
            ["user_id", "device_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_user_b_id"), ["user_b_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_user_a_id"), ["user_a_id"], unique=False
        )

    # ### end Alembic commands ###
