"""remove null contrain on send_at in newsletter

Revision ID: f15e91b70fe8
Revises: 4c50c7ddc13b
Create Date: 2026-04-23 05:04:36.579802

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f15e91b70fe8"
down_revision: Union[str, Sequence[str], None] = "4c50c7ddc13b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.alter_column(
            "send_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.alter_column(
            "send_at", existing_type=postgresql.TIMESTAMP(timezone=True), nullable=False
        )

    # ### end Alembic commands ###
