"""add paid to suborder_enum

Revision ID: f3bd4b2a414d
Revises: 9544435c3a8e
Create Date: 2025-11-28 17:38:35.163011

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3bd4b2a414d"
down_revision: Union[str, Sequence[str], None] = "9544435c3a8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE suborder_status_enum ADD VALUE IF NOT EXISTS 'paid'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
