"""add institution but make it optional now

Revision ID: fb1a4c09a912
Revises: ffd33de0d150
Create Date: 2026-04-06 16:15:07.645502

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb1a4c09a912"
down_revision: Union[str, Sequence[str], None] = "ffd33de0d150"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("waitlists", schema=None) as batch_op:
        batch_op.alter_column("institution", existing_type=sa.VARCHAR(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("waitlists", schema=None) as batch_op:
        batch_op.alter_column("institution", existing_type=sa.VARCHAR(), nullable=False)

    # ### end Alembic commands ###
