"""add platform to waitlist model and profile_pic to user model

Revision ID: fcd5de1a1e10
Revises: 8ab6e03fb2c6
Create Date: 2026-05-10 16:08:43.751100

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcd5de1a1e10"
down_revision: Union[str, Sequence[str], None] = "8ab6e03fb2c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def _index_exists(table_name: str, index_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return any(
        index["name"] == index_name for index in inspector.get_indexes(table_name)
    )


def _constraint_exists(table_name: str, constraint_name: str) -> bool:
    bind = op.get_bind()
    schema = bind.dialect.default_schema_name
    return (
        bind.execute(
            sa.text(
                """
                SELECT 1
                FROM pg_constraint c
                JOIN pg_class t ON t.oid = c.conrelid
                JOIN pg_namespace n ON n.oid = t.relnamespace
                WHERE n.nspname = :schema
                  AND t.relname = :table_name
                  AND c.conname = :constraint_name
                LIMIT 1
                """
            ),
            {
                "schema": schema,
                "table_name": table_name,
                "constraint_name": constraint_name,
            },
        ).first()
        is not None
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists("conversations"):
        with op.batch_alter_table("conversations", schema=None) as batch_op:
            if _index_exists("conversations", "ix_conversations_user_a_id"):
                batch_op.drop_index(batch_op.f("ix_conversations_user_a_id"))
            if _index_exists("conversations", "ix_conversations_user_b_id"):
                batch_op.drop_index(batch_op.f("ix_conversations_user_b_id"))

    if _table_exists("refresh_tokens"):
        with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
            if _constraint_exists("refresh_tokens", "uix_user_device"):
                batch_op.drop_constraint(batch_op.f("uix_user_device"), type_="unique")

    if _table_exists("users"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.add_column(sa.Column("profile_pic", sa.JSON(), nullable=True))

    if _table_exists("waitlists"):
        with op.batch_alter_table("waitlists", schema=None) as batch_op:
            batch_op.add_column(sa.Column("platform", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if _table_exists("waitlists"):
        with op.batch_alter_table("waitlists", schema=None) as batch_op:
            batch_op.drop_column("platform")

    if _table_exists("users"):
        with op.batch_alter_table("users", schema=None) as batch_op:
            batch_op.drop_column("profile_pic")

    if _table_exists("refresh_tokens"):
        with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
            batch_op.create_unique_constraint(
                batch_op.f("uix_user_device"),
                ["user_id", "device_id"],
                postgresql_nulls_not_distinct=False,
            )

    if _table_exists("conversations"):
        with op.batch_alter_table("conversations", schema=None) as batch_op:
            batch_op.create_index(
                batch_op.f("ix_conversations_user_b_id"), ["user_b_id"], unique=False
            )
            batch_op.create_index(
                batch_op.f("ix_conversations_user_a_id"), ["user_a_id"], unique=False
            )

    # ### end Alembic commands ###
