"""add platform to waitlist model and profile_pic to user model

Revision ID: fcd5de1a1e10
Revises: 8ab6e03fb2c6
Create Date: 2026-05-10 16:08:43.751100

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fcd5de1a1e10"
down_revision: Union[str, Sequence[str], None] = "8ab6e03fb2c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_conversations_user_a_id"))
        batch_op.drop_index(batch_op.f("ix_conversations_user_b_id"))

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uix_user_device"), type_="unique")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_pic", sa.JSON(), nullable=True))

    with op.batch_alter_table("waitlists", schema=None) as batch_op:
        batch_op.add_column(sa.Column("platform", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("waitlists", schema=None) as batch_op:
        batch_op.drop_column("platform")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("profile_pic")

    with op.batch_alter_table("refresh_tokens", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uix_user_device"),
            ["user_id", "device_id"],
            postgresql_nulls_not_distinct=False,
        )

    with op.batch_alter_table("conversations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_conversations_user_b_id"), ["user_b_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_conversations_user_a_id"), ["user_a_id"], unique=False
        )

    # ### end Alembic commands ###
