"""add reference_token to order table

Revision ID: ff15258a9ee7
Revises: 81c9b04dcc14
Create Date: 2025-11-26 15:20:44.196181

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff15258a9ee7"
down_revision: Union[str, Sequence[str], None] = "81c9b04dcc14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(table_name: str) -> bool:
    inspector = sa.inspect(op.get_bind())
    return inspector.has_table(table_name)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("orders"):
        return
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("idempotent_key", sa.String(), nullable=False))
        batch_op.add_column(sa.Column("reference_token", sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ["reference_token"])
        batch_op.create_unique_constraint(None, ["idempotent_key"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists("orders"):
        return
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("reference_token")
        batch_op.drop_column("idempotent_key")

    # ### end Alembic commands ###
