"""replace institution with location

Revision ID: ffd33de0d150
Revises: 06a6b87f1747
Create Date: 2026-04-06 16:02:58.309417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffd33de0d150'
down_revision: Union[str, Sequence[str], None] = '06a6b87f1747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(), nullable=False))
        batch_op.drop_column('institution')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waitlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('location')

    # ### end Alembic commands ###
